### ISSUE TITLE
Addresses in Texas Like '# Country Road 212' should be parsed differently

### ISSUE THREAD

**Issue by REWDevinMcBeth** [datamade/usaddress#100]
So I am attempting to parse the address: "1 COUNTRY ROAD 212"
Which is giving the following output: (note I am parsing the result it into JSON format) 
```JSON
[{"AddressNumber": "1"}, {"StreetName": "COUNTRY"}, {"StreetNamePostType": "ROAD"}, {"OccupancyIdentifier": "212"}]
```

When in Texas it uses the `Country Road #` as a street name for the rural areas.
Output should be something like:
```JSON
[{"AddressNumber": "1"}, {"StreetName": "COUNTRY ROAD 212"}]
```

I assume that something `Country Rd 212` should be parsed with the same idea as above.

This is kind of a corner case, but I thought I should post an issue report anyways :+1:

**Comment by cathydeng** [comment]
thanks for reporting - we've run into issues with weird rural Texas roads before. what's the source of this address? do you have more addresses where this came from?

**Comment by REWDevinMcBeth** [comment]
I can list out a bunch of addresses that are similar:

`1901 Country Road 183 Carbon TX 76435`
`10 Country Road 3668 Splendora TX 77372`
`1954 Country Road 43 Greenville TX 75401`
`118 Country Road 46 Hondo TX 78861`
`14442 Country Road 546 Nevada TX 75173`

It looks like from the data that I have there are also some with named country roads:

`109 Country Road Ranchette Corsicana TX 75109`
`104 Country Road Ranchette Corsicana TX 75109`
`116 Country Road Ranchette Corsicana TX 75109`


If I find any more, I will post them up in this same post.

**Comment by cathydeng** [comment]
didn't train on the country road ranchette addresses b/c I was unable to find the addresses on google maps, but now the parser is pretty good at recognizing 'country road' as StreetNamePreType. let us know if you run into other patterns that stump the parser, though

**Comment by REWDevinMcBeth** [comment]
Awesome, looks great! Thanks a lot :+1:
