### ISSUE TITLE
Bad Parse Santa Fe NM

### ISSUE THREAD

**Issue by RyanMTB** [datamade/usaddress#102]
All of the following addresses are tagged with a PlaceName of "Santa" and a StateName of "Fe NM"

311 Montezuma Ave Santa Fe NM 8750
150 Washington Ave., Suite 204 Santa Fe NM 87501
123 E Marcy St Ste 201 Santa Fe NM 87501
1000 Cordova Place, # 234 Santa Fe NM 87505
130 Grant Ave Ste 203 Santa Fe NM 87501

```Python
usaddress.tag("311 Montezuma Ave Santa Fe NM 87501")
```
(OrderedDict([('AddressNumber', u'311'), ('StreetName', u'Montezuma'), ('StreetNamePostType', u'Ave'), ('PlaceName', u'Santa'), ('StateName', u'Fe NM'), ('ZipCode', u'87501')]),
 'Street Address')

These are real addresses.

**Comment by cathydeng** [comment]
really useful examples, thank you! I'll add these addresses to the training data.

**Comment by RyanMTB** [comment]
Here are a few more examples from California

6002 El Tordo Rancho Santa Fe CA 92067
12631 Imperial Hgwy Santa Fe CA 90670
PO Box 9580 Rancho Santa Fe CA 92067

These have a state name of. "Fe CA"

Thanks you for the awesome tool!
