### ISSUE TITLE
Unable to run the measure performance tool.

### ISSUE THREAD

**Issue by envs** [datamade/usaddress#111]
The measure_performance.py is incomplete. The link to training does not get resolved. The new training package has readTrainingData instead of parseTrainingData. Unable to get it to work even after a main and calling into one of the functions.

**Comment by cathydeng** [comment]
hey @envs - `measure_performance.py` is out of date, and the tests there have been moved to `tests/test_labeling.py` - those tests will run w/ `nosetests .`
