### ISSUE TITLE
Address not Parsed Properly

### ISSUE THREAD

**Issue by ckeeney** [datamade/usaddress#113]
I tried parsing this address using the web interface.  The address was found here:
http://www.tdcj.texas.gov/unit_directory/unit_information.html

P.O. Box 48, Substation #1; Galveston, TX 77555 

The semicolon appears to be what they use for a newline delimitter in the table

**Comment by cathydeng** [comment]
what would the correct parsing be?

**Comment by cjkeeney** [comment]
Probably Substation should be the SubaddressType, but I'm not really sure.  Right now it throws the Substation in PlaceName.  It also puts Galveston in the PlaceName and this causes an exception.

For my purposes, I don't know what the substation is for when delivering mail so I just removed it from the string before giving it to the parser.

**Comment by jeancochrane** [comment]
Added this into a bunch of new training data for PO Boxes. Thanks @ckeeney!
