### ISSUE TITLE
Zip code parse issue

### ISSUE THREAD

**Issue by bahromquadevs** [datamade/usaddress#115]
Following address text has issue with parse zipcode

90 lumsden Av Winnipeg MB  R2Y 0J7

'R2Y 0J7'  should be zipcode.

**Comment by fgregg** [comment]
Sorry, unfortunately usaddress doesn't not support Canadian addresses.If
you want make an address parser for Canada, we'd be happy to help.

On Thu, Oct 29, 2015 at 7:46 PM, bahromquadevs <notifications@github.com>
wrote:

> Following address text has issue with parse zipcode
>
> 90 lumsden Av Winnipeg MB R2Y 0J7
>
> 'R2Y 0J7' should be zipcode.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datamade/usaddress/issues/115>.
>



-- 
773.888.2718
