### ISSUE TITLE
ATTN: address line is causing problems with usaddress.tag(addr)

### ISSUE THREAD

**Issue by neybar** [datamade/usaddress#120]
The address looks like this:
123 EAST Street ST,ATTN: ACCOUNTS PAYABLE,PO 12345,City,ST,11111,US

**Comment by cathydeng** [comment]
hey @neybar - thanks for reporting. do you have some real world addresses with this pattern that we can add to the training data? (don't need that many addresses to learn a new pattern, 2-5 would be plenty)

**Comment by jeancochrane** [comment]
The line went dead, so I'm closing this :(

@neybar: if you run into this issue again feel free to open a new issue!
