### ISSUE TITLE
Error in valid address

### ISSUE THREAD

**Issue by nerdlinger** [datamade/usaddress#121]
Have an address: Forest 104 Route, Cottonwood, AZ 86326, USA (Not valid for mailing as this is on USFS land)
Location is approximately here: https://maps.google.com/maps?ll=34.696843,-112.128114&q=34.696843,-112.128114%20
Returned this error: PARSED TOKENS:    [('Forest', 'USPSBoxGroupType'), ('104', 'USPSBoxGroupID'), ('Route,', 'USPSBoxGroupType'), ('Cottonwood,', 'PlaceName'), ('AZ', 'StateName'), ('86326,', 'ZipCode'), ('USA', 'CountryName')]
UNCERTAIN LABEL:  USPSBoxGroupType

Looks like it thinks this forest road is a postal deliver route.

**Comment by fgregg** [comment]
Interesting. Do you have more examples like this?

**Comment by nerdlinger** [comment]
Just starting to use usaddress, so not many ...

Found a similar error at this location: https://goo.gl/maps/aFt7BRRWD6P2
Google Maps provides the address Forest 413 Route, Dewey, AZ 86327
Nearly identical error.

Also https://goo.gl/maps/aZYLbV8gnkz with address Forest 132 Route, Dewey, AZ 86327

**Comment by fgregg** [comment]
What is the correct way to tag this?

**Comment by nerdlinger** [comment]
I might tag it ...
`(OrderedDict([('StreetNamePreType',` 'Forest'), ('StreetName', '132'), ('StreetNamePostType', 'Route'), ('PlaceName', 'Dewey'), ('StateName', 'AZ'), ('ZipCode', '86327')]), 'Ambiguous')

I got that by changed the word Route to Road.

As an example of a correct nearby address, I used this point: https://goo.gl/maps/byD6Zzsg1KS2 with address Forest Service 318 Rd, Jerome, AZ 86331 and the script returned:
`(OrderedDict([('CornerOf',` 'Forest'), ('StreetNamePreType', 'Service'), ('StreetName', '318'), ('StreetNamePostType', 'Rd'), ('PlaceName', 'Jerome'), ('StateName', 'AZ'), ('ZipCode', '86331')]), 'Ambiguous')

**Comment by jeancochrane** [comment]
Hey @nerdlinger,

Sorry for the long wait! Thanks for filing this issue.

I'm nervous about adding in US Forest Service Routes if they're not valid mailing addresses. I also can't find anything about them in the [US Thoroughfare, Landmark, and Postal Address Standard](http://www.urisa.org/advocacy/united-states-thoroughfare-landmark-and-postal-address-data-standard/), which we use for tagging addresses. ([PDF version here.](http://www.urisa.org/clientuploads/directory/GMI/Professional%20Practice/Address%20Standard/AddressStandard_Approved_Apr11_02Content.pdf)) Your guess seems reasonable, but unless we can verify that it sticks to the standard I'm hesitant to consider it official.

What's your use case here? Have you been getting tripped up on this problem a lot? If you can give me a little more info about what you're up to, we can decide whether or not this is something we want to incorporate into the training data.

**Comment by jeancochrane** [comment]
Hey @nerdlinger,

It's been a week, so I'm assuming that this isn't a pressing issue. Given our lack of good examples and documentation standards for US Forest Service Routes, I'm going to leave the model as-is. If you work with more US Forest Service data in the future, feel free to open up a new issue and we can work through it together!
