### ISSUE TITLE
address not parsed correctly - incorrect city 

### ISSUE THREAD

**Issue by jayzeng** [datamade/usaddress#122]
Thanks for the great library, really like it!

4228 SW Dawson Street - Unit 22, Webster Apartments, Seattle, WA 98136

``` python
In [1]: import usaddress

In [2]: usaddress.tag('4228 SW Dawson Street - Unit 22, Webster Apartments, Seattle, WA 98136')
Out[2]:
(OrderedDict([('AddressNumber', u'4228'), ('StreetNamePreDirectional', u'SW'), ('StreetName', u'Dawson'), ('StreetNamePostType', u'Street'), ('OccupancyType', u'Unit'), ('OccupancyIdentifier', u'22'), ('PlaceName', u'Webster Apartments, Seattle'), ('StateName', u'WA'), ('ZipCode', u'98136')]),
 'Street Address'
```

PlaceName contains 'Webster Apartments'. Let me know if you need other details

**Comment by cathydeng** [comment]
hey @jayzeng thanks for reporting - do you happen to have more addresses like this in your dataset?

**Comment by jayzeng** [comment]
hey @cathydeng - another one I have (which is from the same building) is:

4228 SW Dawson Street - Unit 37, Webster Apartments, Seattle, WA 98136

**Comment by jeancochrane** [comment]
Added to the training data. Thanks @jayzeng!
