### ISSUE TITLE
Parsing failure: 1 Washington Square Village

### ISSUE THREAD

**Issue by subsetpark** [datamade/usaddress#123]
Washington Square Village is a superblock in New York City, and 1 Washington Square Village is a valid address in that complex.

``` python
>>> street = "1 washington square village"
>>> usaddress.parse(street)
[(u'1', 'BuildingName'), (u'washington', 'BuildingName'), (u'square', 'BuildingName'), (u'village', 'BuildingName')]
>>> usaddress.tag(street)
(OrderedDict([('BuildingName', u'1 washington square village')]), 'Ambiguous')
```

**Comment by fgregg** [comment]
So, how would you parse this?

**Comment by subsetpark** [comment]
Either:

```py
(u'1', 'AddressNumber'), (u'washington square', 'StreetName'), (u'village', 'StreetNamePostType')
```

or 

```py
(u'1', 'AddressNumber'), (u'washington square', 'BuildingName'), (u'village', 'StreetNamePostType')
```

Depending on whether it's considered valid to combine an `AddressNumber` with a `BuildingName`.

**Comment by fgregg** [comment]
Is there a street called "Washington Square Village"?

**Comment by subsetpark** [comment]
I don't know where it falls in the usaddress ontology... according to Wikipedia, "Washington Square Village (WSV) is an apartment complex in a superblock in the Greenwich Village neighborhood of New York City."

So, it is an entity that supports addressing by `AddressNumber` (1 Washington Square Village, 4 Washington Square Village, etc). In this respect it's like a Street. Physically, of course, it's not a street, it's more like a Building. I don't know if there's a precedent for a single Building supporting multiple Address Numbers.

**Comment by jeancochrane** [comment]
One of my good friends grew up in 1 Washington Square Village, so I checked in with him about how the address works. Here's his take:

> the four buildings are just [1-4] Washington Square Village
>
> as if WSV is the street name
>
> [individual apartments are the] same as any other apartment building
>
> apartment [2-16][A-z]

So "Washington Square Village" is technically a building name, but it stands in for the StreetName when you're e.g. sending mail to an apartment in the building. Note that there's no actual StreetName component to the address:

>must be because those streets used to go through
>
>but now they're just driveways

Given all this, here's my guess on how to tag "1 Washington Square Village Apt 2A New York NY 10012":

| String | Parsed type |
| --- | --- |
| 1 | AddressNumber | 
| Washington Square Village | BuildingName | 
| Apt | OccupancyType | 
| 2A | OccupancyIdentifier | 
| New York | PlaceName | 
| NY | StateName | 
| 10012 | ZipCode | 

We have a choice to make here: we can try to create some training data specifically for this apartment complex, or we can acknowledge that it's a historical accident and let it be. Leaving that decision up to @fgregg.

**Comment by fgregg** [comment]
Tag it in accordance to reality. Don't try to outsmart the learner.

**Comment by jeancochrane** [comment]
Words to live by. I'll add it to the training data.
