### ISSUE TITLE
P.O. Box in Box Elder, Montana

### ISSUE THREAD

**Issue by rsimoes** [datamade/usaddress#124]
A curve ball for the parser:

```
ORIGINAL STRING:  PO BOX 195; BOX ELDER, MT 59521-0269
PARSED TOKENS:    [(u'PO', 'USPSBoxType'), (u'BOX', 'USPSBoxType'), (u'195;', 'USPSBoxID'), (u'BOX', 'USPSBoxType'), (u'ELDER,', 'PlaceName'), (u'MT', 'StateName'), (u'59521-0269', 'ZipCode')]
UNCERTAIN LABEL:  USPSBoxType
```

Parsed tokens should be:

```
[(u'PO BOX', 'USPSBoxType'), (u'195;', 'USPSBoxID'), (u'BOX ELDER', 'PlaceName'), (u'MT', 'StateName'), (u'59521-0269', 'ZipCode')]
```

**Comment by cathydeng** [comment]
hey @rsimoes - thanks for reporting. do you have any more addresses from box elder? or any other addresses where 'box' is an address token other than `USPSBoxType`?

**Comment by jeancochrane** [comment]
Well, this is a fun edge case, isn't it? Added this and a few more addresses from Box Elder, MT to the training data. Thanks @rsimoes!
