### ISSUE TITLE
PO BOX labeled individually when tagging

### ISSUE THREAD

**Issue by ybordag** [datamade/usaddress#128]
PO and BOX were labeled separately as individual tokens as USPSBoxType

It comes from 'PO BOX 4900 DEPT 505 SCOTTSDALE AZ 85261-4900'

this raised an error message in the .tag method.

**Comment by cathydeng** [comment]
that's probably not the source of the error in the tag method - 'PO' & 'BOX' should be individual tokens after parsing, & the tag method concatenates consecutive tokens w/ the same label. can you drop in the output of the parse method & the error you get w/ the tag method?

**Comment by ybordag** [comment]
Traceback (most recent call last):
  File "C:/Users/yebordag/PycharmProjects/tester3/Tester3.py", line 37, in <module>
    addresstag2(testSet1)
  File "C:/Users/yebordag/PycharmProjects/tester3/Tester3.py", line 29, in addresstag2
    print usaddress.tag(x)
  File "C:\Python27\lib\site-packages\usaddress\__init__.py", line 190, in tag
    raise RepeatedLabelError(address_string, parse(address_string), label)
usaddress.RepeatedLabelError: 
ERROR: Unable to tag this string because more than one area of the string has the same label

ORIGINAL STRING:  PO BOX 4900 DEPT 505 SCOTTSDALE AZ 85261-4900
PARSED TOKENS:    [(u'PO', 'USPSBoxType'), (u'BOX', 'USPSBoxType'), (u'4900', 'USPSBoxID'), (u'DEPT', 'USPSBoxType'), (u'505', 'USPSBoxID'), (u'SCOTTSDALE', 'PlaceName'), (u'AZ', 'StateName'), (u'85261-4900', 'ZipCode')]
UNCERTAIN LABEL:  USPSBoxType

When this error is raised, it's likely that either (1) the string is not a valid person/corporation name or (2) some tokens were labeled incorrectly

To report an error in labeling a valid name, open an issue at https://github.com/datamade/usaddress/issues/new - it'll help us continue to improve probablepeople!

For more information, see the documentation at http://usaddress.readthedocs.org/

Process finished with exit code 1

(The entire error message)

I think I understand the error now, the parser thinks DEPT is a postbox type when it means department and that 505 is the post box number instead of the dept number.

Thanks

**Comment by jeancochrane** [comment]
We have a bunch of incoming training data using departments, so this should be resolved by the next release.
