### ISSUE TITLE
usaddress.RepeatedLabelError

### ISSUE THREAD

**Issue by pramsey** [datamade/usaddress#129]
Feel free to close this out.

```
KASLO CRK SOUTH FORK RD, WOODBURY CREEK, BC
```

This string reads like a real address (it has all the usual parts, and I as a human can figure out what they are), so perhaps usaddress should have been able to handle it. On the other hand, it appears to not actually be a real place in BC (at least not by any formal standard) so maybe it's fine that it failed.

http://apps.gov.bc.ca/pub/geocoder/addresses.geojson?addressString=KASLO+CRK+SOUTH+FORK+RD,+WOODBURY+CREEK,+BC

It's "real" though, in that it appears on a voters list.

**Comment by jeancochrane** [comment]
Weird! We also don't support Canadian addresses, so that could be a source of error.

Hope everything else worked out for you – feel free to open another issue if you need more support.
