### ISSUE TITLE
mis-parsing texas country road street names

### ISSUE THREAD

**Issue by cansar** [datamade/usaddress#130]
ORIGINAL STRING:  615 Co Rd 45300, Powderly, Tx 75473
PARSED TOKENS:    [(u'615', 'AddressNumber'), (u'Co', 'StreetName'), (u'Rd', 'StreetNamePostType'), (u'45300,', 'ZipCode'), (u'Powderly,', 'PlaceName'), (u'Tx', 'StateName'), (u'75473', 'ZipCode')]
UNCERTAIN LABEL:  ZipCode

This is a real residential address in Texas.

**Comment by cathydeng** [comment]
what should the 45300 be?

**Comment by cansar** [comment]
Thanks for the quick response! The name of the road is "Co Rd 45300" which stands for "County Road 45300". Texas apparently has many road names that are a short abbreviation followed by a number. Other examples include "3800 County Road 94", "101 Pr 140" (Private Road 140), "2225 Cr 494" (Also County Road but in this case Cr instead of Co.).

**Comment by cathydeng** [comment]
ah gotcha - yeah, we've run into tricky texas names before. can you drop a few examples of full address strings from your data where the street name is a series of numbers? we can add this to the training data.

**Comment by cansar** [comment]
Here are some more examples. I'm going to look into training the library myself too and see if I can get more examples:

UNCERTAIN LABEL:  StreetNamePostType
2407 Jefferson Ave N, Mt Pleasant, Tx 75455-5918

UNCERTAIN LABEL:  StreetName
3665 Anderson County Rd 312, Frankston, Tx 75763
8213 Shady Oaks Dr, North Richland Hills, Tx 76182 (This seems like a rather simple example)
6520 Stone Creek Dr, North Richland Hills, Tx 76182
8617 Terrell Dr, North Richland Hills, Tx 76182 (Here it's the city that gets parsed as a street)
6252 Dream Dust Dr, North Richland Hills, Tx 76180
3389 Anderson County Rd 452, Palestine, Tx 75803
6252 Dream Dust Dr, North Richland Hills, Tx 76180

# UNCERTAIN LABEL:  ZipCode
38 Private Road 54606, Pittsburg, Tx 75686

**Comment by jeancochrane** [comment]
Added these in to the training data; expect better support in the next release. Thanks @cansar!
