### ISSUE TITLE
lauderdale by the sea parsed incorrectly

### ISSUE THREAD

**Issue by spiritbear** [datamade/usaddress#134]
Hi,

We have a few addresses in Florida that are being parsed incorrectly. e.g
1. Input String: 274 Basin Dr,lauderdale by the sea,FL,33308
   `[('274', 'AddressNumber'), ('Basin', 'StreetName'), ('Dr,', 'StreetNamePostType'), ('lauderdale', 'PlaceName'), ('by', 'StateName'), ('the', 'PlaceName'), ('sea,', 'PlaceName'), ('FL,', 'StateName'), ('33308', 'ZipCode')]`
2. Input String: 4461 W TRADEWINDS AVE,apt 901,LAUDERDALE BY THE SEA,FL,33308-4464
   `
   [('4461', 'AddressNumber'), ('W', 'StreetNamePreDirectional'), ('TRADEWINDS', 'StreetName'), ('AVE,', 'StreetNamePostType'), ('apt', 'OccupancyType'), ('901,', 'OccupancyIdentifier'), ('LAUDERDALE', 'PlaceName'), ('BY', 'StateName'), ('THE', 'PlaceName'), ('SEA,', 'PlaceName'), ('FL,', 'StateName'), ('33308-4464', 'ZipCode')]
   `
   Lauderdale by the Sea should be classified as a Single PlaceName. Happy to add ore examples to this list.

**Comment by jeancochrane** [comment]
Hey @spiritbear, 

Thanks for flagging this! We'd be glad to incorporate your addresses as training data. The best way to do this would be to [train and tag the data yourself](https://github.com/datamade/usaddress#how-to-use-this-development-code-for-the-nerds) and then submit a pull request. Happy to walk you through that process if you need help!

**Comment by jeancochrane** [comment]
Seems like this isn't going anywhere – we'll need more examples to fix this pattern. Closing for now. @spiritbear, feel free to reopen if you'd like to contribute!
