### ISSUE TITLE
Unnecessary dependency on metafone in setup.py

### ISSUE THREAD

**Issue by ThijsMergaert** [datamade/usaddress#135]
Looking at setup.py, the install_requires line lists 'metafone' as a dependency.  However, I can't find where in the code this dependency is actually used. I've tried removing it and running the build/test steps in the README, and can't notice any difference.  Is there any reason I'm overlooking why it's there?  If not, I'm happy to submit a PR to remove it.

**Comment by jeancochrane** [comment]
Sorry for the long wait, @ThijsMergaert! Thanks for bearing with us.

I also can't find any use of metafone, although I leave the final call up to @fgregg, who knows more about the guts of this library than I do. Either way, we're happy to look at PRs. Pull away!
