### ISSUE TITLE
some street addresses that get labeled incorrectly

### ISSUE THREAD

**Issue by cathydeng** [datamade/usaddress#136]
should add some of these to the training data

8130 JOHN W CARPENTER FWY
775 COMMERCE PARKWAY WEST DR
7102 LAKEVIEW PARKWAY WEST DR
8720 CASTLE CREEK PARKWAY EAST DR
9320 PRIORITY WAY WEST DR
5293 LAKEVIEW PARKWAY SOUTH DR
3665 PRIORITY WAY SOUTH DR
5975 CASTLE CREEK PARKWAY NORTH DR
2611 WATERFRONT PARKWAY EAST DR
5750 CASTLE CREEK PARKWAY NORTH DR
5451 LAKEVIEW PARKWAY SOUTH DR
50 W FALL CREEK PARKWAY NORTH DR
6040 E PLEASANT RUN PARKWAY SOUTH DR
1150 N WHITE RIVER PARKWAY W DR
7114 LAKEVIEW PARKWAY WEST DR
4270 THE CIRCLE AT NORTH HILLS ST
160 PARK AT NORTH HILLS ST

**Comment by jeancochrane** [comment]
Added to the next batch of training data. Thanks @cathydeng!
