### ISSUE TITLE
Repeated Label error

### ISSUE THREAD

**Issue by kevinhippert** [datamade/usaddress#137]
This address 981 SAINT ALBANS ST. N. #303 generates this error. Saint Albans is the street name. 

`Traceback (most recent call last):
  File "address_parsing.py", line 98, in <module>
    writevalue = line.strip() + ';' + parse_address(line)
  File "address_parsing.py", line 50, in parse_address
    sap = usaddress.tag(line)
  File "C:\Python27\lib\site-packages\usaddress__init__.py", line 190, in tag
    raise RepeatedLabelError(address_string, parse(address_string), label)
usaddress.RepeatedLabelError:
ERROR: Unable to tag this string because more than one area of the string has the same label

ORIGINAL STRING:  981 SAINT ALBANS ST. N. #303

PARSED TOKENS:    [(u'981', 'AddressNumber'), (u'SAINT', 'StreetName'), (u'ALBANS', 'StreetName'), (u'ST.', 'StreetNamePostType'), (u'N.', 'StreetNamePreDirectional'), (u'#', 'StreetName'), (u'303\n', 'StreetName')]
UNCERTAIN LABEL:  StreetName

When this error is raised, it's likely that either (1) the string is not a valid person/corporation name or (2) some tok
ens were labeled incorrectly

To report an error in labeling a valid name, open an issue at https://github.com/datamade/usaddress/issues/new - it'll help us continue to improve probablepeople!`

**Comment by jeancochrane** [comment]
Hey @kevinhippert,

This looks like an identical error to the one referenced [in this issue](https://github.com/datamade/usaddress/issues/144). Applying a similar fix, I'm able to work around the error:

```python
# Add a comma after the street direction post-type
In [1]: usaddress.tag('981 SAINT ALBANS ST. N., #303')

Out[1]:
(OrderedDict([('AddressNumber', '981'),
              ('StreetName', 'SAINT ALBANS'),
              ('StreetNamePostType', 'ST.'),
              ('StreetNamePostDirectional', 'N.'),
              ('OccupancyIdentifier', '# 303')]),
 'Street Address')
```

We're working on building in better support for this type of address, but for now, see if you can preprocess your addresses to add in commas in these cases. If you need help with that feel free to reopen this issue and I'd be glad to advise.
