### ISSUE TITLE
City and State not parsed

### ISSUE THREAD

**Issue by js333031** [datamade/usaddress#140]
Please see code and result below 
`p = usaddress.tag(addr)`
`print(p)`

`123 Main St,Foo,NJ`
`(OrderedDict([('AddressNumber', '123'), ('StreetName', 'Main'), ('StreetNamePostType', 'St')]), 'Street Address')`

Version:
Python 3.5.2 (default, Jul  5 2016, 12:43:10)

**Comment by fgregg** [comment]
Can't reproduce:

```python
>>> import usaddress
>>> usaddress.tag('123 Main St,Foo,NJ')
(OrderedDict([('AddressNumber', '123'), ('StreetName', 'Main'), ('StreetNamePostType', 'St'), ('PlaceName', 'Foo'), ('StateName', 'NJ')]), 'Street Address')
```

Try do a fresh install from pypi.
