### ISSUE TITLE
Issue with direction in city name

### ISSUE THREAD

**Issue by gs377209** [datamade/usaddress#142]
Please find the issue below. It seems that the parsing is failing due to a direction in the city name "North Little Rock"

`ORIGINAL STRING:  1921 N. Main St. North Little Rock,AR 72114
PARSED TOKENS:    [(u'1921', 'AddressNumber'), (u'N.', 'StreetNamePreDirectional'), (u'Main', 'StreetName'), (u'St.', 'StreetNamePostType'), (u'North', 'StreetNamePreDirectional'), (u'Little', 'StreetName'), (u'Rock,', 'PlaceName'), (u'AR', 'StateName'), (u'72114', 'ZipCode')]
UNCERTAIN LABEL:  StreetNamePreDirectional`

**Comment by jeancochrane** [comment]
Hey @gs377209, 

Thanks for filing this. We're working on this problem, as you can in [this issue](https://github.com/datamade/usaddress/issues/144). If you still need to parse this type of address, I'd recommend a similar solution to the one I outlined in the issue above. Adding a comma to separate the StreetName from the PlaceName gives me the right behavior:

```python
In [4]: usaddress.tag('1921 N. Main St., North Little Rock,AR 72114')

Out[4]:
(OrderedDict([('AddressNumber', '1921'),
              ('StreetNamePreDirectional', 'N.'),
              ('StreetName', 'Main'),
              ('StreetNamePostType', 'St.'),
              ('PlaceName', 'North Little Rock'),
              ('StateName', 'AR'),
              ('ZipCode', '72114')]),
 'Street Address')
```

If you need help figuring out how to preprocess your addresses to add commas in the right places, let me know and I'd be glad to help. I'm going to close this for now, and I'll tag you in the previous issue I listed if we wind up incorporating a global fix for this type of problem.

**Comment by gs377209** [comment]
Thank you very much for the feedback. I will try to add the commas in if possible.
