### ISSUE TITLE
How can i parse uk address

### ISSUE THREAD

**Issue by saybinem** [datamade/usaddress#143]
For example i have address **10-20 Kingsland Road, Hackney, London, E2 8DA, United Kingdom** in this format .
_i want to return it in_ 
Street address = 10-20 Kingsland Road
Locality = Hackney
Zip code =  E2 8DA
Country =United Kingdom

**Comment by jeancochrane** [comment]
Hi @saybinem, 

Sorry for the long wait! Thanks for bearing with us.

Unfortunately, we don't currently have plans to support parsing addresses outside of the United States. Sorry! If you're interested in contracting DataMade to develop a parser specific to your project, feel free to [get in touch](https://datamade.us/contact-us/).
