### ISSUE TITLE
Recipient tagged as Subaddress Type

### ISSUE THREAD

**Issue by TheSimpleMachine** [datamade/usaddress#148]
usaddress.parse('JANET S SMITH 7710 MAIN AVE APT 1110 LOS ANGELES CA 9151-2100 ')

Appears to be where the name could be a street name and the middle initial is directional (N, S, E, W).

Output looks like
JANET, SubaddressType
S, SubaddressIdentifier
SMITH, SubaddressType

Using usaddress.tag fails, since there are two SubaddressType seperated by SubaddressIdentifier. 

Perhaps if there is a sequence of SubaddressType > SubaddressIdentifier > SubaddressType > followed by valid address tags, to assign bigger weight towards that combo being a Recipient rather than Subaddress.

**Comment by jeancochrane** [comment]
Take a look at my response in #149. Closing this for now, since it seems like a corollary to that issue.
