### ISSUE TITLE
Rearrange order of `LABELS` in __init__.py

### ISSUE THREAD

**Issue by tanyaschlusser** [datamade/usaddress#157]
It would make it a little easier to do manual tagging if the fields in the `LABELS` list are sort of in the positions they normally would be in an address.

**Comment by jeancochrane** [comment]
Done! I also pushed this as a new release to PyPi, so you'll be able to use it if you 
`pip install --upgrade usaddress` to the latest version (v0.5.9).

Thanks again @tanyaschlusser - happy tagging!
