### ISSUE TITLE
Verify training data in f731af

### ISSUE THREAD

**Issue by jeancochrane** [datamade/usaddress#161]
I added training data from `unparseable.csv` before I had a solid understanding of the existing training data and the URISA standard. I'm wondering if this is contributing to depreciating performance in #153 and #155.

I'm going to look through the new training data in [f731af](https://github.com/datamade/usaddress/commit/f731afdb58f32c47c0fea9ba2f79ebea4c26ad63) and verify that it 1) meets the URISA standard and 2) does not include excessive examples of unusual address patterns.

**Comment by shikharcic** [comment]
Can you please tell which features you passed to crf-suite implementation ? Also, what was the encoder used ?

**Comment by fgregg** [comment]
@shikharcic please open a new issue. This is not relevant for this issue.

@jeancochrane, do not remove unusual patterns.

**Comment by jeancochrane** [comment]
Closing this – will keep the unusual patterns.
