### ISSUE TITLE
Tool to merge tagged data back down to simple address fields

### ISSUE THREAD

**Issue by mlissner** [datamade/usaddress#162]
In our DB we have the fields:

 - name
 - address1
 - address2
 - city
 - state
 - zip

And we're using this library to convert between a string address with newlines into those fields. It seems though, like this is a pretty complicated thing to figure out:

 - Handling of PO Boxes?
 - Handling of Street Addresses?
 - Which fields are address1 and which are address2?
 - Etc.

It'd be great if this library had a function to merge the output from `tag` into the kinds of fields that might be in a database like ours.

**Comment by cathydeng** [comment]
hey @mlissner! this feature exists (relevant commit [here](https://github.com/datamade/usaddress/commit/e7ad26691985e9f60b611d2857616a687dea9366)) but it's undocumented (sorry DataMaids)

you can pass an optional argument to the tag method like so: `usaddress.tag(my_addr, tag_mapping=my_mapping)`
where `my_mapping` is a dict, w/ existing usaddress labels as keys & the corresponding fields in your db as values

**Comment by mlissner** [comment]
Oye! This would have saved us a lot of time trying to reinvent the wheel. Two thoughts:

1. I'll get this documented.
2. Is there an appetite for some default mapping variables? I think the scheme above is pretty common and it might be nice to include a mapping var to achieve it. Not sure what name we'd give the variable (`COMMON_ADDRESS_MAPPING`?), but I could put that in a PR too if we wanted, since I'll need to make it for my own purposes one way or another.

If we get the variable landed, how quickly can we get a release out?

**Comment by cathydeng** [comment]
re: default mapping variables, my hunch is that there would be way too much variation in what people need for it to make sense as something that lives in usaddress instead of something that gets passed in as an arg. imo it'd make more sense to have a good documented example that people can copy/paste. but I'll let the DataMade folks decide on that.

**Comment by mlissner** [comment]
Ah, didn't realize you weren't a DataMade person at first. I'll take a stab just updating the docs. It's easier anyway, and we won't need a release for that either.
