### ISSUE TITLE
RepeatedLabelError when street name contains a number

### ISSUE THREAD

**Issue by luser** [datamade/usaddress#167]
Hi there, thanks for providing this module, it's super useful! I'm trying to use it to parse addresses that in a dataset that came from our county's Voter Registration office, but I'm having problems with some of the addresses. Specifically, some of the addresses have a street name that contains a number, because the street name is just 'STATE ROUTE NNN', for example:
```python

>>> usaddress.tag('261  STATE ROUTE 590  ELMHURST TWP, PA  18444')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/luser/.pyenv/versions/2.7.11/lib/python2.7/site-packages/usaddress/__init__.py", line 178, in tag
    label)
usaddress.RepeatedLabelError: 
ERROR: Unable to tag this string because more than one area of the string has the same label

ORIGINAL STRING:  261  STATE ROUTE 590  ELMHURST TWP, PA  18444
PARSED TOKENS:    [(u'261', 'AddressNumber'), (u'STATE', 'StreetNamePreType'), (u'ROUTE', 'StreetNamePreType'), (u'590', 'AddressNumber'), (u'ELMHURST', 'StreetName'), (u'TWP,', 'PlaceName'), (u'PA', 'StateName'), (u'18444', 'ZipCode')]
UNCERTAIN LABEL:  AddressNumber

When this error is raised, it's likely that either (1) the string is not a valid person/corporation name or (2) some tokens were labeled incorrectly

To report an error in labeling a valid name, open an issue at https://github.com/datamade/usaddress/issues/new - it'll help us continue to improve probablepeople!

For more information, see the documentation at https://usaddress.readthedocs.io/
```

Here's the full list of addresses that hit this error from the dataset: [addresses.txt](https://github.com/datamade/usaddress/files/767145/addresses.txt)

**Comment by jeancochrane** [comment]
Hey @luser,

Thanks for filing this issue! I can add your list of addresses to our next round of training data. If this pattern error is blocking your work, there are two steps you can take to work around it:

1. Preprocess your addresses to add commas  before the PlaceName in the case of State Route addresses, e.g.:

```python
In [3]: usaddress.tag('261  STATE ROUTE 590,  ELMHURST TWP, PA  18444')
Out[3]:
(OrderedDict([('AddressNumber', '261'),
              ('StreetNamePreType', 'STATE ROUTE'),
              ('StreetName', '590'),
              ('PlaceName', 'ELMHURST TWP'),
              ('StateName', 'PA'),
              ('ZipCode', '18444')]),
 'Street Address')
```

2. [Retrain the model locally](https://github.com/datamade/usaddress/blob/master/training/README.md) with your new training data. Remember to make a PR so we can bring your changes in!

Either works well for us – let me know what you decide. 

-jean

**Comment by luser** [comment]
I resorted to the typical hack of "prefilter the data with a regex" which worked well enough to get me through what I needed to do. :)

**Comment by jeancochrane** [comment]
Great to hear! Let us know if any more issues come up. I'll keep this issue open until your training data is added to a new release, at which point I'll close it.
