### ISSUE TITLE
comma included in the name of the parsed StreetNamePostType

### ISSUE THREAD

**Issue by GeoAC1984** [datamade/usaddress#171]
After parsing with usaddress.parse, the name of the StreetNamePostType contains comma in it, like in 'AVENUE,'. 

Also state label is applied incorrectly. See example dataset in the attachment.
[address_sample.zip](https://github.com/datamade/usaddress/files/800397/address_sample.zip)

**Comment by GeoAC1984** [comment]
Hi @jeancochrane,

Thanks, tag method indeed is better suitable for my purpose. Here is a bigger address sample from the dataset.  Addresses on the lines 1447, 1708, 2250, 4603, 4756, 5872 and 6731 were also assigned state token in error.  I believe LH is just an apartment number; this data is real property sales from the NYC Finance Department. 

[address_sample.zip](https://github.com/datamade/usaddress/files/810998/address_sample.zip)

**Comment by jeancochrane** [comment]
Awesome, thanks @GeoAC1984! I'll add those addresses to the next round of training data and close this when it gets incorporated.
