### ISSUE TITLE
Transform the abbreviations of street name post type?

### ISSUE THREAD

**Issue by yuanxu-li** [datamade/usaddress#174]
`>>>addr='123 Main St. Suite 100 Chicago, IL'`
`>>> usaddress.parse(addr)`
`(OrderedDict([('AddressNumber', u'123'), ('StreetName', u'Main'), ('StreetNamePostType', u'St.'), ('OccupancyType', u'Suite'), ('OccupancyIdentifier', u'100'), ('PlaceName', u'Chicago'), ('StateName', u'IL')]), 'Street Address')`

It would be nice if we can transform the abbreviation of street name post type (or more fields), by passing another parameter to usaddress, as in:
`>>> usaddress.parse(addr, abbr=False)`
`(OrderedDict([('AddressNumber', u'123'), ('StreetName', u'Main'), ('StreetNamePostType', u'Street'), ('OccupancyType', u'Suite'), ('OccupancyIdentifier', u'100'), ('PlaceName', u'Chicago'), ('StateName', u'IL')]), 'Street Address')`

This can be very useful for people like me who are dealing with a lot of address comparisons.

**Comment by jeancochrane** [comment]
Hey @yuanxu-li,

The main focus for usaddress is parsing, not cleaning, so I think this is ultimately out of scope for the library.

That being said, I think it's an interesting problem, so I'd be curious to hear how you're solving it. I could also imagine developing a section of the docs to point people toward resources (or strategies) for cleaning and post-processing.

**Comment by jeancochrane** [comment]
I'm going to close this for now so that we can keep the issues list clean @yuanxu-li, but if you want to reopen this discussion in the future you'd be very welcome!
