### ISSUE TITLE
Pip Install fails in Python 3.6.1 Visual Studio 14

### ISSUE THREAD

**Issue by kevinhippert** [datamade/usaddress#182]
When i run "Pip Install usaddress" on Python 3.6.1 with Microsoft Visual C++ Build Tools 14 installed. I get this output from pip:

[From my cursory research, this seems to be the relevent Stackover exhange](https://stackoverflow.com/questions/27754492/vs-2015-compiling-cocos2d-x-3-3-error-fatal-error-c1189-error-macro-definiti)

When i run "Pip Install usaddress" on Python 3.6.1 with Microsoft Visual C++ Build Tools 14 installed. I get this output from pip:

PS C:\Users\username> pip install usaddress
Collecting usaddress
  Using cached usaddress-0.5.10-py2.py3-none-any.whl
Requirement already satisfied: future>=0.14 in c:\python36-32\lib\site-packages (from usaddress)
Collecting python-crfsuite>=0.7 (from usaddress)
  Using cached python-crfsuite-0.9.2.tar.gz
Requirement already satisfied: probableparsing in c:\python36-32\lib\site-packages (from usaddress)
Installing collected packages: python-crfsuite, usaddress
  Running setup.py install for python-crfsuite ... error
    Complete output from command c:\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\username\\AppData\\Local\\Temp\\pip-build-njxh2q_f\\python-crfsuite\\setup.p
y';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\username\AppData\Local\Temp\pip-m
nccjaaw-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.6
    creating build\lib.win32-3.6\pycrfsuite
    copying pycrfsuite\_dumpparser.py -> build\lib.win32-3.6\pycrfsuite
    copying pycrfsuite\_logparser.py -> build\lib.win32-3.6\pycrfsuite
    copying pycrfsuite\__init__.py -> build\lib.win32-3.6\pycrfsuite
    running build_ext
    building 'pycrfsuite._pycrfsuite' extension
    creating build\temp.win32-3.6
    creating build\temp.win32-3.6\Release
    creating build\temp.win32-3.6\Release\pycrfsuite
    creating build\temp.win32-3.6\Release\crfsuite
    creating build\temp.win32-3.6\Release\crfsuite\lib
    creating build\temp.win32-3.6\Release\crfsuite\lib\crf
    creating build\temp.win32-3.6\Release\crfsuite\lib\crf\src
    creating build\temp.win32-3.6\Release\crfsuite\swig
    creating build\temp.win32-3.6\Release\crfsuite\lib\cqdb
    creating build\temp.win32-3.6\Release\crfsuite\lib\cqdb\src
    creating build\temp.win32-3.6\Release\liblbfgs
    creating build\temp.win32-3.6\Release\liblbfgs\lib
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Icrfsuite/include/ -Icrfsuite/lib/cqdb/include -Iliblbfgs/include -Ipycrfsuite -Icrf
suite/win32 -Iinclude -Ic:\python36-32\include -Ic:\python36-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10
.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /E
Hsc /Tppycrfsuite/_pycrfsuite.cpp /Fobuild\temp.win32-3.6\Release\pycrfsuite/_pycrfsuite.obj
    _pycrfsuite.cpp
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Icrfsuite/include/ -Icrfsuite/lib/cqdb/include -Iliblbfgs/include -Ipycrfsuite -Icrf
suite/win32 -Iinclude -Ic:\python36-32\include -Ic:\python36-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10
.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /E
Hsc /Tppycrfsuite/trainer_wrapper.cpp /Fobuild\temp.win32-3.6\Release\pycrfsuite/trainer_wrapper.obj
    trainer_wrapper.cpp
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Icrfsuite/include/ -Icrfsuite/lib/cqdb/include -Iliblbfgs/include -Ipycrfsuite -Icrf
suite/win32 -Iinclude -Ic:\python36-32\include -Ic:\python36-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10
.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /E
Hsc /Tccrfsuite/lib/crf/src\crf1d_context.c /Fobuild\temp.win32-3.6\Release\crfsuite/lib/crf/src\crf1d_context.obj
    crf1d_context.c
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\math.h(262): warning C4005: 'isfinite': macro redefinition
    crfsuite/include/os.h(49): note: see previous definition of 'isfinite'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefinition
    crfsuite/include/os.h(50): note: see previous definition of 'snprintf'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Library function declarati
on
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2

Command "c:\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\username\\AppData\\Local\\Temp\\pip-build-njxh2q_f\\python-crfsuite\\setup.py';f=getattr(tokenize, '
open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\username\AppData\Local\Temp\pip-mnccjaaw-record\install-r
ecord.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\username\AppData\Local\Temp\pip-build-njxh2q_f\python-crfsuite\

**Comment by fgregg** [comment]
Unfortunately, this is an upstream problem https://github.com/scrapinghub/python-crfsuite/issues/51

**Comment by fgregg** [comment]
this has been resolved
