### ISSUE TITLE
After parse, default human readable print

### ISSUE THREAD

**Issue by invious** [datamade/usaddress#183]
I really wanted to use this to unify all addresses in a table that have been entered all kinds of ways, to one default way of entering the address, e.g. the ZIP4 format the USPS uses:

```
123 HAPPY ST NW
WASHINGTON DC 20002-4414
```
without this, i have to figure out a way to use the dict elements to recontruct an address from the parts..? How can I do this

**Comment by fgregg** [comment]
Let's continue the conversation at #83.
