### ISSUE TITLE
'Business' Routes are incorrectly tagged

### ISSUE THREAD

**Issue by tebrown** [datamade/usaddress#186]
`import usaddress
usaddress.tag('1200 Business 190 ste 13, COVINGTON, LA 70433')
`

Expected Result:
`ORIGINAL STRING:  1200 Business 190 ste 13, COVINGTON, LA 70433
PARSED TOKENS:    [('1200', 'AddressNumber'), ('Business 190', 'StreetName'), ('ste', 'OccupancyType'), ('13,', 'OccupancyIdentifier'), ('COVINGTON,', 'PlaceName'), ('LA', 'StateName'), ('70433', 'ZipCode')]
`

Actual Result:
`
ORIGINAL STRING:  1200 Business 190 ste 13, COVINGTON, LA 70433
PARSED TOKENS:    [('1200', 'AddressNumber'), ('Business', 'StreetName'), ('190', 'OccupancyIdentifier'), ('ste', 'OccupancyType'), ('13,', 'OccupancyIdentifier'), ('COVINGTON,', 'PlaceName'), ('LA', 'StateName'), ('70433', 'ZipCode')]
UNCERTAIN LABEL:  OccupancyIdentifier
`

In many places, 'Business' roads are the original highway, which has since been replaced with a bypass, which is now known as the proper route name.

**Comment by jeancochrane** [comment]
Fixed in [8bc4224.](https://github.com/datamade/usaddress/commit/8bc42249f3440c81e45364ab06c0d7b9ec5442be)
