### ISSUE TITLE
Add missing STREET_NAMES

### ISSUE THREAD

**Issue by tebrown** [datamade/usaddress#190]
I have come across several street names that are used, but not included in `usaddress/__init__.py`.  The list is below:

```{'bl', 'causway', 'ci', 'ck', 'cr', 'crecent', 'cresent', 'crscnt', 'crssing', 'crt', 'ex', 'havn', 'height', 'hgts', 'la', 'lanes', 'lp', 'mi', 'mile', 'mn', 'overlook', 'ovlk', 'pk', 'plaines', 'prarie', 'pw', 'pwy', 'ri', 'rise', 'rn', 'strave', 'te', 'tl', 'tpk', 'tr', 'trpk', 'turn', 'xc', 'xg'}```

This relates to #189

**Comment by jeancochrane** [comment]
Closed by [ab00738](https://github.com/datamade/usaddress/commit/ab00738b5596876f83a08d8ad53f6ff1c97a509b). Thanks for your work @tebrown!
