### ISSUE TITLE
Error on street SOUTH PARK RANCH ROAD SOUTH FORK

### ISSUE THREAD

**Issue by cliffordsnow** [datamade/usaddress#196]
When I run "SOUTH PARK RANCH ROAD SOUTH FORK", a name found in Teton County, through usaddress.tag it errors out with the following message: 

```UNCERTAIN LABEL:  StreetNamePostType
When this error is raised, it's likely that either (1) the string is not a valid person/corporation name or (2) some tokens were labeled incorrectly```

**Comment by jeancochrane** [comment]
Hey @cliffordsnow,

This is a pretty unusual pattern for our training set. Do you have a lot of this kind of address pattern in your dataset? And if so, how would you expect this string to be tagged?

**Comment by cliffordsnow** [comment]
I did a query of the US and it only came up one other time. (Just South Fork)  So I agree it's an outlier and okay not to train on. I'm trying to created a postgresql python function to expand county road names using usaddress. I just happened to pick a county with unusual street names. I'll close this issue with no action required.

**Comment by fgregg** [comment]
Thanks for all your work on openstreetmap, btw @cliffordsnow.
