### ISSUE TITLE
Which module is used by the web interface

### ISSUE THREAD

**Issue by zhangjinzhou** [datamade/usaddress#200]
I generated a module using training/labeled.xml and parsed an address 1060 4TH PACE SOUTH STREET SAINT JOHNS 85936. In the result, "1060 4TH" is tagged as address number which is wrong.
Another model generated using measure_performance/test_data/labeled.xml can parse this address correctly.
Then I generated third module using both of the datasets and it doesn't work.
The address can be correctly parsed in your web interface https://parserator.datamade.us/usaddress

Should we edit training/labeled.xml to fix this issue?
How can we access the module or training dataset you use for the web interface?

**Comment by jeancochrane** [comment]
The web API is using the most recent version of the package on PyPi, which is [v0.5.10](https://github.com/datamade/usaddress/releases/tag/v0.5.10). You can use that version by running `pip install usaddress`.

Seems like between our last release and now, performance has depreciated with regards to this particular pattern. Do you have any more examples of the pattern? If so, we can attempt a fix by bringing the addresses in as new training data.

**Comment by zhangjinzhou** [comment]
@jeancochrane I am using the current version (v0.5.10). When I run `usaddress.parse('1060 4TH PACE SOUTH STREET SAINT JOHNS 85936')`, it gives me the correct result.

However, as a developer, I trained my own module based on training/labeled.xml. When I parse this address with the module, I get the wrong result.

Shouldn't I use training/labeled.xml to get a base module? I thought labeled.xml is the dataset you used at back-end.

**Comment by jeancochrane** [comment]
`training/labeled.xml` is indeed the training set that we use on the back-end, but we've added new training data since v0.5.10, so the model will be slightly different between v0.5.10 and the `master` branch. (Training your own model based on `training/labeled.xml` is similar to building a `dev` version of usaddress.) Does that make sense?

**Comment by zhangjinzhou** [comment]
Yes this solved my problem. Thank you!

**Comment by zhangjinzhou** [comment]
I finally figured it out. The `parse` method works well but the `tag` method doesn't. What's the difference of the two methods?
