### ISSUE TITLE
trouble training new data

### ISSUE THREAD

**Issue by hurnhu** [datamade/usaddress#216]
I've added 20 addresses for training, tagged them, and then trained using ```parserator train training/labeled.xml,training/new_addresses.xml usaddress```.

but when I try to test the new traning with ```parserator label measure_performance/test_data/new_tests.csv measure_performance/test_data/new_tests.xml usaddress``` it still recommends the incorrect tags. the tags that it is recommending are exactly the same as the ones it recommenced when training. is this becuase i installed usaddress via pip first and then downloaded the git repo? as it does not seem to be using the new training model.

**Comment by jeancochrane** [comment]
It's possible that the version of usaddress that you got via pip is taking priority over the new model in your Python `PATH`. IIRC you should be able to run `pip install -e <path/to/usaddress>` to install a local version of a package with pip. You could also run `pip uninstall usaddress` first just to make sure you've cleared out the old version. Does that end up fixing your issue?

**Comment by hurnhu** [comment]
Yes this was due t the pip install taking over. Creating a python virtual
environment fixed the problem

**Comment by jeancochrane** [comment]
Awesome! Closing this then. Feel free to open a new issue if you run into more problems.
