### ISSUE TITLE
Unable to install on macOS 14.0 with Python 3.12

### ISSUE THREAD

**Issue by aprknight** [datamade/usaddress#356]
The title says it all
[pip_install.log](https://github.com/datamade/usaddress/files/12848454/pip_install.log)

**Comment by mxm-c** [comment]
I'm in the same boat. 
Looks like this is the thread to bump and watch: https://github.com/scrapinghub/python-crfsuite/pull/153
Most likely as soon as crfsuite gets an update we'll be able to install usaddress.

**Comment by fgregg** [comment]
should work now
