### ISSUE TITLE
Better handling of special characters

### ISSUE THREAD

**Issue by fgregg** [datamade/usaddress#43]
I hacked together a temporary solution for ampersands, https://github.com/datamade/us-address-parser/commit/9cc63adde6cada7890a5cfb28984afbd9aac28a9#diff-5253508931d87b3c5f701f1d50a83d6bR33

We need something better.

**Comment by jeancochrane** [comment]
Do we still need this to be addressed?

**Comment by fgregg** [comment]
yes.

**Comment by jeancochrane** [comment]
Great. Assigning it to myself – we can talk it over soon.

**Comment by fgregg** [comment]
closed by https://github.com/datamade/parserator/commit/f61465e82867f94daf5e781d8f3b498b0713d061
