### ISSUE TITLE
Specify prerequisite packages?

### ISSUE THREAD

**Issue by waldoj** [datamade/usaddress#47]
You might consider specifying that a couple of packages have to be installed in Ubuntu/Debian for this to work. (I'm running Ubuntu 12.04.) Attempting to install it throws cryptic errors unless g++ and python-dev have been installed, like such:

```
apt-get install g++
apt-get install python-dev
```

OTOH, I only have about six months of serious Python experience, and that's mostly in writing Python (not participating in the Python software ecosystem), so perhaps this is common knowledge.

**Comment by jeancochrane** [comment]
I'm planning to set up a partition for Ubuntu on my machine sometime in the next few weeks; will plan to double-check and update installation instructions.

**Comment by fgregg** [comment]
We could do this, or we could just provide binary builds. for mac os and windows.

**Comment by jeancochrane** [comment]
Sounds fun! Assigning myself.

**Comment by fgregg** [comment]
Okay, windows and mac users now have binary builds for their dependencies. We are not going to provide linux binary builds any time too soon, so let's give instructions for those users

**Comment by jeancochrane** [comment]
Thanks for setting that up @fgregg. I'll keep this open until I can update the docs with Linux install instructions, most likely the first week of January.

**Comment by fgregg** [comment]
Let's provide manylinux builds. We'll need to adapt https://github.com/pypa/python-manylinux-demo for https://github.com/scrapinghub/python-crfsuite

@jeancochrane let's talk about this.

**Comment by jeancochrane** [comment]
After two years, this is finally done! All of the dependencies are now manylinux-compatible 💥📣🎉

**Comment by derekeder** [comment]
![ytbzzckrqceja](https://cloud.githubusercontent.com/assets/919583/25721078/ce10fe5c-30d4-11e7-8872-38156f73cdf0.gif)
