### ISSUE TITLE
in output, merge consecutive tokens w/ same label

### ISSUE THREAD

**Issue by cathydeng** [datamade/usaddress#55]
e.g. say we have the address string '123 Main St, New York'...currently 'New York' is split into 'New' + 'York' and both are labeled as city. It would be more intuitive if consecutive tokens w/ the same label were merged in output, so that we end up w/ 'New York' as city.

**Comment by sapper9** [comment]
Please fix this issue of multiple labels for the same token.
Currently it is generating multiple Street names and City names if the string contains spaces.

Example : 65 W Red Oak Ln is generating two "Street names" .

Parsed String= [('65', 'AddressNumber'), ('W', 'StreetNamePreDirectional'), ('Red', 'StreetName'), ('Oak', 'StreetName'), ("Ln']", 'StreetNamePostType')]

**Comment by cathydeng** [comment]
hi @sapper9 - we are keeping the parse method as is, so that it doesn't merge any tokens. however, if you use the tag method, you'll get a tuple w/ (1) tagged tokens w/ appropriate merges & (2) street address type (either 'Street Address' 'Intersection' 'PO Box' or 'Ambiguous'):
```
>>> usaddress.tag('65 W Red Oak Ln')
(OrderedDict([('AddressNumber', '65'), ('StreetNamePreDirectional', 'W'), ('StreetName', 'Red Oak'), ('StreetNamePostType', 'Ln')]), 'Street Address')
```

**Comment by sapper9** [comment]
Thanks this saved me a lot of work !
Cheers!

**Comment by cathydeng** [comment]
glad to hear it :grinning:
