### ISSUE TITLE
AddressNumberPrefixes aren't recognized

### ISSUE THREAD

**Issue by darrell** [datamade/usaddress#60]
For instance:
0108 SW PALATINE HILL RD,PORTLAND,OR 97219

This is an unusual feature of some addresses in Portland, Oregon. It's specifically addressed in section 2.2.1.4 of the United States Thoroughfare, Landmark, and Postal Address Data Standard.

It should be 

AddressNumberPrefix: 0
AddressNumber: 108

Similarly, as mentioned in that section, some Puerto Rico addresses use leading letters.

Further, there are areas of Genesee County, MI that regularly using leading 'G's,

For instance: G1075 N Ballenger Hwy, Flint, MI 48504

These should all be put into AddressNumberPrefix, as AddressNumber is meant to be an integer under the standard.

**Comment by jeancochrane** [comment]
Any plans to implement this @fgregg? Might be a case of post-processing that is best left to the user.

**Comment by fgregg** [comment]
We are not going to implement this.
