### ISSUE TITLE
Help parsing

### ISSUE THREAD

**Issue by fgregg** [datamade/usaddress#71]
@cathydeng thought on how to parse: 

harborside financial center, plaza ii, 1st floor

**Comment by cathydeng** [comment]
it looks like harborside financial center is a business complex in NJ, and each of their buildings are named 'plaza N'. so maybe:

<PlaceName>harborside</PlaceName>
<PlaceName>financial</PlaceName>
<PlaceName>center,</PlaceName>
<BuildingName>plaza</BuildingName>
<BuildingName>ii,</BuildingName>
<OccupancyIdentifier>1st</OccupancyIdentifier>
<OccupancyType>floor</OccupancyType>

**Comment by cathydeng** [comment]
jk not PlaceName. instead of making a separate tag for building complexes, these should just all be tagged BuildingName

```
<BuildingName>harborside</BuildingName>
<BuildingName>financial</BuildingName>
<BuildingName>center,</BuildingName>
<BuildingName>plaza</BuildingName>
<BuildingName>ii,</BuildingName>
<OccupancyIdentifier>1st</OccupancyIdentifier>
<OccupancyType>floor</OccupancyType>
```

**Comment by fgregg** [comment]
Thanks, what about this bad boy?!

215 n. loop 1604 e. apt 720

**Comment by fgregg** [comment]
7490 n. cr 650 e.
