### ISSUE TITLE
FL is being idententified as OccupancyType

### ISSUE THREAD

**Issue by meher404** [datamade/usaddress#75]
Many clean records with FL as state are not getting parsed.
I figured it was a version problem, and actually it was. Some of the FL records were parsed properly with 0.2.4. But, there still are some FL records that are not getting parsed. 

Example: TIMOTHY ADAMS HEADQU ORLANDO FL 328990001

The Web API (0.2.4, i guess) returns : "BuildingName","BuildingName","BuildingName","BuildingName","OccupancyType","OccupancyIdentifier"
"TIMOTHY","ADAMS","HEADQU","ORLANDO","FL","328990001" 

And 0.3.1 returns:
>>usaddress.parse("TIMOTHY ADAMS HEADQU ORLANDO FL 328990001")
[('TIMOTHY', 'BuildingName'), ('ADAMS', 'BuildingName'), ('HEADQU', 'BuildingName'),
 ('ORLANDO', 'BuildingName'), ('FL', 'OccupancyType'), ('328990001', 'OccupancyIdentifier')]

This is just one example. I get this problem only with some FL state records. All the other 49 states work fine for me.

**Comment by cathydeng** [comment]
hey @meher404 - thanks for pointing this out!

it looks like this is happening b/c (1) 'FL' sometimes indicates floor, which is an occupancy type, and (2) there aren't that many examples of addresses with this pattern (building instead of street, all caps, no comma, 9 digit zip) in our training data

can you send over a few examples of addresses that the parser is failing on, as well as some other addresses with similar patterns? I can re-train the model

**Comment by meher404** [comment]
I am afraid i am not authorized to give you the data. 

Is there a way i can myself add the samples in the training data and prepare the model?

**Comment by cathydeng** [comment]
usaddress learns pretty quickly, and only requires a few examples (for example, 5 is probably plenty) before it picks up on new patterns, so I wouldn't need a full dataset. But if that's still an issue, you could add training data and create your own address parser model using our [parserator](https://github.com/datamade/parserator) toolkit. There's some documentation in the readme for this repo as well - all you need is a csv with the raw address strings you want to add. I'm happy to help if you have any questions about using parserator.

**Comment by meher404** [comment]
Thanks for the tip. but, i think ill first train it on my own.
Where can i get the source code of 0.2.4 version? [2.4 is giving me better results then 0.3.1]

**Comment by cathydeng** [comment]
this is the code at 0.2.4: https://github.com/datamade/usaddress/tree/9a33386f0d592f4ba23f317be7986c9fa9525ba0

**Comment by cathydeng** [comment]
closing b/c the parser performs well on FL addresses that have a street address, & unable to find real address examples w/ building+city+state+zip pattern
