### ISSUE TITLE
usaddress.tag failing but web interface works.

### ISSUE THREAD

**Issue by sapper9** [datamade/usaddress#77]
Code to Replicate the error:
_________________________
import usaddress 

vud_SAL1_STR='1775 Broadway And 57th, Newyork NY'       
vud_SAL1_STR_Tagged=usaddress.tag((vud_SAL1_STR))         
print "Tagged Dict=",vud_SAL1_STR_Tagged
______________________________________________________
Error Message:
Traceback (most recent call last):
  File "C:\Python27\my_scripts\test_usaddress_Error.py", line 5, in <module>
    vud_SAL1_STR_Tagged=usaddress.tag((vud_SAL1_STR))
  File "C:\Python27\lib\site-packages\usaddress\__init__.py", line 114, in tag
    return (tagged_address, address_type)
UnboundLocalError: local variable 'address_type' referenced before assignment

**Comment by fgregg** [comment]
what do you mean "failing"?

**Comment by sapper9** [comment]
I have uploaded the code and example to replicate the error and also the error message.
Working on a windows 7 machine (64-bit) and have Python 2.79 and usaddress-0.3.2-py2.7 installed.

**Comment by sapper9** [comment]
This above code with a different address works.
import usaddress 

vud_SAL1_STR='100 Broadway st Newyork NY'    
vud_SAL1_STR_Tagged=usaddress.tag((vud_SAL1_STR))         
print "Tagged Dict=",vud_SAL1_STR_Tagged

______________________________________
here is the output:
Tagged Dict= (OrderedDict([('AddressNumber', '100'), ('StreetName', 'Broadway'), ('StreetNamePostType', 'st'), ('PlaceName', 'Newyork'), ('StateName', 'NY')]), 'Street Address')

**Comment by fgregg** [comment]
Thanks! Very helpful.
