### ISSUE TITLE
add examples from St. Paul police dept

### ISSUE THREAD

**Issue by cathydeng** [datamade/usaddress#82]
there are tricky intersection addresses like:
- 7 ST E & LAFAYETTE
- 4 ST E & JACKSON

& a bunch of addresses w/ X at the end of the address number

http://www.stpaul.gov/index.aspx?NID=4638

**Comment by fgregg** [comment]
Let's give tag the address numbers with XX's as "Block Number"

**Comment by jeancochrane** [comment]
Where did this end up?

**Comment by fgregg** [comment]
Didn't implement, and I think it was a good idea not to.
