### ISSUE TITLE
Windows installation - problems with compiling

### ISSUE THREAD

**Issue by michaelsorich** [datamade/usaddress#84]
Hi,

I am having some troubles installing usaddress on windows (windows 7 64 bit, python 2.7 32 bit) using pip and am hoping you may be able to give some hints on compiler settings that work on windows. It appears that visual studio 8 is not able to compile it and that g++ is required. I tried installing mingw (both 32 and 64) but run into errors. The last part of the command output is below but I do not have insight into what I am doing wrong or what is wrong with my setup. Any hints would be appreciated.

Michael

c:/mingw/bin/../lib/gcc/mingw32/4.5.2/../../../../mingw32/bin/ld.exe: build\temp.win32-2.7\Release\pycrfsuite\_pycrfsuite.o: bad reloc address 0xc in section `.data'

collect2: ld returned 1 exit status
    
error: command 'g++' failed with exit status 1

**Comment by michaelsorich** [comment]
Update: The problem related to the installation of python-crfsuite on windows. The solutions can be found here - https://github.com/tpeng/python-crfsuite/issues/16, although hopefully the python-crfsuite package will be updated to automatically avoid this issue in future.

**Comment by fgregg** [comment]
I put in a fix upstream in python-crfsuite. It's in the repo but hasn't been pushed to pypi.

**Comment by tpeng** [comment]
@fgregg i just pushed it to pypi.
