### ISSUE TITLE
'&' in Street Name Parses as Intersection

### ISSUE THREAD

**Issue by apidevsm** [datamade/usaddress#85]
Here is an address with an ampersand in the street name.  This parsed as an intersection with an Ambiguous address type.

1176 TOWN & COUNTRY CMNS, CHESTERFIELD, MO, 63017

**Comment by BlvdJoe** [comment]
Just adding two-cents on this one: This also happens with building names (e.g. "M & E Bank Building, Fake City, UT, 12345")

**Comment by fgregg** [comment]
@apidevsm's address is now being parsed correctly, but not @BlvdJoe's

**Comment by fgregg** [comment]
added @BlvdJoe 's example to the training
