### ISSUE TITLE
definitions for address tags

### ISSUE THREAD

**Issue by derekeder** [datamade/usaddress#86]
Currently, we just list the different available address tags, but don't provide definitions. For users to translate these tags to their own data model, these definitions would be very useful.

    AddressNumber
    StreetName
    PlaceName
    StateName
    ZipCode
    AddressNumberPrefix
    AddressNumberSuffix
    StreetNamePreDirectional
    StreetNamePostDirectional
    StreetNamePreModifier
    StreetNamePostType
    StreetNamePreType
    USPSBoxType
    USPSBoxID
    USPSBoxGroupType
    USPSBoxGroupID
    LandmarkName
    CornerOf
    IntersectionSeparator
    OccupancyType
    OccupancyIdentifier
    SubaddressIdentifier
    SubaddressType
    Recipient
    BuildingName
    NotAddress

**Comment by fgregg** [comment]
Nearly everything comes from here. 

http://www.urisa.org/advocacy/united-states-thoroughfare-landmark-and-postal-address-data-standard/

**Comment by cathydeng** [comment]
that address standard documentation is pretty convoluted & unfriendly tho - it'd be helpful for ppl to easily see a quick definition, as well as some examples of common tokens where applicable. I'll add this to the documentation
