### ISSUE TITLE
more robust labeling tests, to help detect degrading performance

### ISSUE THREAD

**Issue by cathydeng** [datamade/usaddress#90]
currently the tests in test_labeling.py only include address patterns from usaddress' early days. we should probably have a labeled test data file where we contribute an example or two each time we add new patterns to training data

**Comment by fgregg** [comment]
:+1:

**Comment by Downchuck** [comment]
The open-dm-dq may have some good data.
http://code.openhub.net/project?pid=Vxtz-h7heEg&prevcid=1&did=standardizer%2Fdata%2Ftest%2Faddress&cid=NPNtaqAhx-8&fp=8281&projSelected=true

**Comment by jeancochrane** [comment]
We now seem to have a [nice and beefy set of testing data](https://github.com/datamade/usaddress/tree/master/measure_performance/test_data). I've updated the training/testing data documentation in [7a05b1c](https://github.com/datamade/usaddress/commit/7a05b1c1b24f0f9f95c03a79e1e15a94ab0329b2) to encourage contributors to create new testing data, and I'll be appending new tests to `measure_performance/test_data/labeled.xml`. 

After a year and a half, I think it's about time to close this!
