### ISSUE TITLE
Parsing OccupancyIdentifier and OccupancyType When There's a Room and a Floor

### ISSUE THREAD

**Issue by mattalhonte** [datamade/usaddress#96]
Tried to parse this: "22 Reade Street, 2nd Floor Conference Room, New York, NY"

Ideally, I think it should have grabbed "2nd Floor Conference Room" (or possibly just "2nd Floor Conference") as OccupancyIdentifier, and "Room" as OccupancyType.

Instead, it takes "2nd" as OccupancyIdentifier, "Floor" as OccupancyType, and attaches "Conference Room" to the PlaceName (as "Conference Room, New York").

**Comment by cathydeng** [comment]
thanks @mattalhonte! is there more where this address came from? a dataset with more examples of tricky occupancies would be helpful for training the parser.

**Comment by mattalhonte** [comment]
Here's more examples of addresses with both a room and a floor: https://github.com/mattalhonte/CROL-Parsing/blob/master/Planned%20Implementation/Use%20Cases/roomAndFloor.txt

Thanks!

**Comment by cathydeng** [comment]
cool! I'll add these examples to the training data

**Comment by cds-amal** [comment]
Hi @cathydeng, 

I found more variants of floor and room from our sources. Please find them [here](https://goo.gl/eZ3Fi4).

Thanks in advance!
