### ISSUE TITLE
usaddress page isn't parsing anything

### ISSUE THREAD

**Issue by rcackermanCC** [datamade/usaddress#97]
Hey all - I've been trying to use the form on the [usaddress page](https://parserator.datamade.us/usaddress) with no success. It's working on the main parserator page, but no results return on the usaddress page.

usaddress page after clicking the parse button:
![screenshot 2015-06-12 10 16 06](https://cloud.githubusercontent.com/assets/10965511/8131976/25752cfa-10ec-11e5-8df5-00655196dfa7.png)

vs main page after clicking the parse button:
![screenshot 2015-06-12 10 16 26](https://cloud.githubusercontent.com/assets/10965511/8131980/2cd13f34-10ec-11e5-9cef-330bf8b63a4f.png)

I'm using Chrome on Mac OSX 10.10.3.

Thanks!

**Comment by derekeder** [comment]
@rcackermanCC looking in to it now!

**Comment by rcackermanCC** [comment]
@derekeder Woah that was scarily fast.

**Comment by derekeder** [comment]
@rcackermanCC fixed! Thanks for letting us know.
