### ISSUE TITLE
Address at University of Missouri breaks in all sorts of ways

### ISSUE THREAD

**Issue by micahsaul** [datamade/usaddress#99]
Address: 115 Business Loop 70 w, Mizzou North, Rm 501 Sponsored Programs Administration Columbia MO 65211
There's a few things going on here:

1) Directional words in the recipient cause the recipient to be parsed as a street name (see also: Kanye West, 1234 Main Street)
2) Possibly because of 1, 115 and 70 are both parsed as street names (this doesn't seem to happen if 'Mizzou North' is removed)
3) "Sponsored Programs Administration Columbia" is parsed as the PlaceName.

Address was found on the SAM.gov website:
https://www.sam.gov/portal/SAM/?navigationalstate=JBPNS_rO0ABXdcACJqYXZheC5mYWNlcy5wb3J0bGV0YnJpZGdlLlNUQVRFX0lEAAAAAQApdmlldzoyM2E4MjAyMS1iOGVhLTRjYTYtOTk3NC02MjM4YWU1OWU0Y2UAB19fRU9GX18*&portal:componentId=7b9b1ff4-9b43-460c-9313-a2fabdc07366&interactionstate=JBPNS_rO0ABXdGABBfanNmQnJpZGdlVmlld0lkAAAAAQAlL2pzZi9lbnRpdHlTZWFyY2gvZW50aXR5U2VhcmNoTmF2LmpzcAAHX19FT0ZfXw**&portal:type=action##11

**Comment by cathydeng** [comment]
I'm not sure I know what the true parsed result should be - what should Mizzou North be labeled as?

Also, can you describe how to get to that address, or other addresses, on the SAM.gov website? The link goes to a generic about page.

**Comment by micahsaul** [comment]
Howdy-

Yeah, I'm not sure how Mizzou North should be parsed either, to be honest. This address is all sorts of messed up. That said, it led me to discover that directionals in the recipient name also break (try Kanye West) (on further inspection, this maybe only happens with a comma after the recipient name ('Kanye West 1234 Main Street' works, but 'Kanye West, 1234 Main Street' doesn't).

The fact that the parser not knowing what to do with 'Mizzou North' breaks the parsing of the preceding portion was interesting to me, as well.

Sorry about that link, I didn't think to check it before pasting. Their links don't seem to work that well. I actually got it from the SAM API (http://gsa.github.io/sam_api/sam/) using DUNS number 153890272, but you can also find it by going to sam.gov, clicking Search Records, searching by DUNS number 153890272, clicking "View Details", and then "Entity Record".

Mizzou North seems to be the name of the campus, so I'm not sure why it's even needed in the address (it likely isn't).

Hope that helps! This library is awesome, BTW! Thanks for the awesome work!

**Comment by cathydeng** [comment]
looks like Mizzou North is the name of a building: https://www.google.com/maps/@38.9672964,-92.3393151,313m/data=!3m1!1e3

this is a good example for teaching the parser, I'll add it to the training data. thank you!

re: directionals in the recipient name, it's tough to do anything about it w/o examples from real data to train on. a directional near the beginning of an address is still much more likely to be a street direction than a recipient, so let's table this for now.

**Comment by cathydeng** [comment]
also, keep us posted if you encounter more weird addresses from the SAM API! this looks like a great potential source of messy addresses
